---
title: "BNStruct"
author: "Stewart Kerr"
date: "April 20, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bnstruct)
library(dplyr)
library(reshape)
library(tidyr)
#library(graph)
#library(Rgraphviz) required to plot DBN

#Tranpose the data for BNDataset
df_unstack <- function(df,start){
  #Height of the stacks
  timepoints <- df[1] %>% unique()
  n_timepoints <- nrow(timepoints)
  
  #Pulls the first n_timepoints rows
  unstack_df <- df[start:(start+n_timepoints-1),]
  
  return(unstack_df)
}

df_widen <- function(unstack_df){
  timepoints <- df[1] %>% unique()
  n_timepoints <- nrow(timepoints)
  
  #Transposes the dataset to get it in the right form for BN
  wide_unstack_df <- data.frame()
  for (tp in 1:n_timepoints){
    wide_unstack_df = c(wide_unstack_df, unstack_df[tp,-1])
  }
  
  return(as.data.frame(wide_unstack_df))
}

wide_unstack_df_combine <- function(df){
  timepoints <- df[1] %>% unique()
  n_timepoints = nrow(timepoints)
  n_obs = nrow(df)/n_timepoints
  
  final_df = data.frame()
  for (i in 1:n_obs){
    start = ((i-1)*n_timepoints)+1
    unstack_df = df_unstack(df,start)
    wide_unstack_df = df_widen(unstack_df)
    final_df = rbind(final_df, wide_unstack_df)
  }
  
  return(final_df)
}

```

```{r Arabidopsis}
#Read in the RData for Arab
load("../output/Clustering.RDATA.RData")
df_clustered = cbind(net$colors, data_no0) %>%
  filter(`net$colors` > 0) %>%
  group_by(`net$colors`)

#Average across clusters
df_clust_avg = summarise_all(df_clustered, mean)

#1 row per cluster per replication
tempdf1 = select(df_clust_avg, cluster = `net$colors`, contains("_1")) %>%
  rename_at(.vars = vars(ends_with("_1")),
            .funs = funs(sub("_1", "", .)))
tempdf2 = select(df_clust_avg, cluster = `net$colors`, contains("_2")) %>%
  rename_at(.vars = vars(ends_with("_2")),
            .funs = funs(sub("_2", "", .)))
#Grab clusters
clusters <- as.character(pull(tempdf1, cluster))
clusters <- paste("C",clusters,sep="")
#Grab timepoints
n_timepoints <- ncol(tempdf1)-1
#Tranpose data
tempdf1 <- t(tempdf1)[2:11,]
colnames(tempdf1) <- clusters
tempdf1 <- as.data.frame(tempdf1) %>%
  rename(clusters) %>%
  mutate(rep = 1, timepoint = rownames(tempdf1))
tempdf2 <- t(tempdf2)[2:11,]
colnames(tempdf2) <- clusters
tempdf2 <- as.data.frame(tempdf2) %>%
  rename(clusters) %>%
  mutate(rep = 2, timepoint = rownames(tempdf2))

arab_clust_avg = rbind(tempdf1,tempdf2) 

arab_clust_avg_reshaped = data.frame()
col.from = colnames(arab_clust_avg)
col.to1 = paste(colnames(arab_clust_avg),"T1",sep="_") #Needed for timepoint names
col.to2 = paste(colnames(arab_clust_avg),"T2",sep="_") #Needed for timepoint names
for (i in seq(from = 1, to = n_timepoints-1)){
  
  d1 = filter(arab_clust_avg, timepoint == paste("M",i,sep="")) %>%
    rename_at(vars(col.from), ~col.to1)
  d2 = filter(arab_clust_avg, timepoint == paste("M",i+1,sep="")) %>%
    rename_at(vars(col.from), ~col.to2)
  d1_1 = filter(d1, rep_T1 == 1)
  d1_2 = filter(d1, rep_T1 == 2)
  d2_1 = filter(d2, rep_T2 == 1)
  d2_2 = filter(d2, rep_T2 == 2)
  all_comb = rbind(cbind(d1_1,d2_1),
                   cbind(d1_1,d2_2),
                   cbind(d1_2,d2_1),
                   cbind(d1_2,d2_2))
  arab_clust_avg_reshaped = rbind(arab_clust_avg_reshaped,all_comb)
}

arab_clust_avg_reshaped2 = unite_(arab_clust_avg_reshaped,"dp", c("rep_T1", "timepoint_T1","rep_T2","timepoint_T2"), sep = "_")

```

```{r}
#DREAM dataset
dream <- read.delim("../data/DREAM4_InSilico_Size10/insilico_size10_1/insilico_size10_1_timeseries.tsv", comment.char="#")

#Get number of timepoints
timepoints <- dream[1] %>% unique()

#Get gene names/numbers
gene_names <- colnames(dream)[-1]
n_genes <- length(gene_names)


bn_ready_df = wide_unstack_df_combine(dream)
```


```{r Dynamic Bayes Net}
#Temporary
var_names <- colnames(select(arab_clust_avg_reshaped2, -dp))

#Creates a BN dataset
bn_df <- BNDataset(data = select(arab_clust_avg_reshaped2, -dp),
                   variables = var_names,
                   discreteness = rep('c',length(clusters)),
                   num.time.steps = 2,
                   node.sizes = rep(3,length(clusters)))

#Examine the dataset
#show(bn_df)

#Attempt to learn network
dbn <- learn.dynamic.network(bn_df, num.time.steps = 2)
#show(dbn)
#cpts(dbn)
x = dag(dbn)
#plot(dbn)
```

```{r Static Bayes Net}
static_df <- select(dream, -Time)

#Create BN dataset
bn_df <- BNDataset(data = static_df,
                   variables = gene_names,
                   discreteness = rep('c',n_genes),
                   node.sizes = rep(2,n_genes))

#Learn static network
bn <- learn.network(bn_df, scoring.func = "BDeu")
plot(bn)
```


```{r Linear Regression}
library("corrplot")
library("glmnet")
library("glasso")
library("stringr")




#Read in DREAM dataset
df <- read.delim("../data/DREAM4_InSilico_Size10/insilico_size10_1/insilico_size10_1_timeseries.tsv", comment.char="#")
dft1 <- df_unstack(df, start = 22)

#Build covariance matrices
arab_cov <- cov(arab_clust_avg[,2:11])
df_cov <- cov(dft1[-1])


#Building network - simple linear regression
grn <- lm(G1 ~ G10+G2+G3+G4+G5+G6+G7+G8+G9, data = df)


#Correlation matrix
#rquery.cormat(df)

#LASSO
glmnet(dream[,3:11], dream[,2], family = "gaussian", alpha = 1, lambda = NULL)

#GLASSO
glasso(df_cov, rho = 0.006)
#glasso(arab_cov, rho=0.05)
```


```{r GeneNet}
# load GeneNet library
library("GeneNet")
# generate random network with 20 nodes and 10 percent edges (=19 edges)
true.pcor <- ggm.simulate.pcor(20, 0.1)
# convert to edge list
test.results <- ggm.list.edges(true.pcor)[1:19,]
######## use graphviz directly to produce a plot ##########
# uncomment for actual use!
#nlab <- LETTERS[1:20]
#ggm.make.dot(filename="test.dot", test.results, nlab, main = "A graph")
#system("fdp -T svg -o test.svg test.dot") # SVG format
######## use Rgraphviz produce a plot ##########
# uncomment for actual use!
nlab <- LETTERS[1:20]
gr <- network.make.graph( test.results, nlab)
gr
num.nodes(gr)
edge.info(gr)
gr2 <- network.make.graph( test.results, nlab, drop.singles=TRUE)
gr2
num.nodes(gr2)
edge.info(gr2)
# plot network
# NOTE: this requires the installation of the "Rgraphviz" library
library("Rgraphviz")
plot(gr, "fdp")
plot(gr2, "fdp")
## for a full example with beautified Rgraphviz plot see
## the example scripts provide with GeneNet (e.g. arabidopis-net.R)
```