gold_at:
		./generate_gold.py -i ../data/Arab.Meristem/arabidopsis.meristem.expression.csv -c "Feature_ID" --delimiter=',' -o ../data/Arab.Meristem/arabidopsis.meristem.biogrid.interactions.csv --pickle ../data/Arab.Meristem/arabidopsis.meristem.biogrid.graph.pickle

gold_atd:
		python3 -m pdb ./generate_gold.py -i ../data/Arab.Meristem/arabidopsis.meristem.expression.csv -c "Feature_ID" --delimiter=',' -o ../data/Arab.Meristem/arabidopsis.meristem.biogrid.interactions.csv --pickle ../data/Arab.Meristem/arabidopsis.meristem.biogrid.graph.pickle

gold_cpib:
		./generate_gold.py -i ../data/CPIB_Lateral_Root_timecourse/E-MTAB-2565-A-AFFY-2-normalized-expressions.tsv --delimiter='\t' -o ../data/CPIB_Lateral_Root_timecourse/CPIB_Lateral_Root.biogrid.interactions.csv --pickle ../data/CPIB_Lateral_Root.biogrid.graph.pickle

gold_cpibd:
		python3 -m pdb ./generate_gold.py -i ../data/CPIB_Lateral_Root_timecourse/E-MTAB-2565-A-AFFY-2-normalized-expressions.tsv --delimiter='\t' -o ../data/CPIB_Lateral_Root_timecourse/CPIB_Lateral_Root.biogrid.interactions.csv --pickle ../data/CPIB_Lateral_Root.biogrid.graph.pickle
