gold:
		./generate_gold.py -i ../data/CPIB_Lateral_Root_timecourse/E-MTAB-2565-A-AFFY-2-normalized-expressions.tsv -o out.json

goldd:
		python3 -m pdb ./generate_gold.py -i ../data/CPIB_Lateral_Root_timecourse/E-MTAB-2565-A-AFFY-2-normalized-expressions.tsv -o out.json
